# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a9e2b2b2136eae08b8676fb0f08ead132db032b2ca65449d147844b80b34f3fbc3bc011236f652b5ed3bff64e1b9d3902e032b8f908326591a4c9a0bd5b92bb

test:
  secret_key_base: 89256c2e3c8a62509427d445575a8c49eb60e3e9e855acca5e896f87931dd41a720e56b1164a559cabd86c2241ed3f7d149bf3550b7c741145025bf4feecc5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
